// This file was auto-generated by Quasalang

import enUS from './en-US'
import fr from './fr'
import de from './de'

export default { 
	'en-US': enUS, // English
	'fr': fr, // French
	'de': de, // German
}